Avoid shell injection in action inputs

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,20 +1,41 @@
-name: 'Setup mold'
-description: 'Install mold as the default linker'
+name: "Setup mold"
+description: "Install mold as the default linker"
+
 inputs:
   mold-version:
-    description: 'The mold version to download'
-    default: '3.0.0'
+    description: "The mold version to download"
+    default: "3.0.0"
   make-default:
-    description: 'Make mold the default linker'
-    default: true
+    description: "Make mold the default linker"
+    default: "true"
+
 runs:
   using: composite
   steps:
     - run: |
         set -x
-        echo "mold ${{ inputs.mold-version }}"
-        if [ "$(whoami)" = root ]; then SUDO=; else SUDO=sudo; fi
-        wget -O- --timeout=10 --waitretry=3 --retry-connrefused --progress=dot:mega https://github.com/rui314/mold/releases/download/v${{ inputs.mold-version }}/mold-${{ inputs.mold-version }}-$(uname -m)-linux.tar.gz | $SUDO tar -C /usr/local --strip-components=1 --no-overwrite-dir -xzf -
-        test ${{ inputs.make-default }} = true -a "$(realpath /usr/bin/ld)" != /usr/local/bin/mold && $SUDO ln -sf /usr/local/bin/mold "$(realpath /usr/bin/ld)"; true
+
+        echo "mold $MOLD_VERSION"
+
+        case "$MAKE_DEFAULT" in
+          true|false) ;;
+          *)
+            echo "::error::make-default must be true or false"
+            exit 1
+            ;;
+        esac
+
+        if [ "$(id -u)" -eq 0 ]; then SUDO=; else SUDO=sudo; fi
+
+        wget -O- --timeout=10 --waitretry=3 --retry-connrefused --progress=dot:mega \
+          "https://github.com/rui314/mold/releases/download/v${MOLD_VERSION}/mold-${MOLD_VERSION}-$(uname -m)-linux.tar.gz" \
+          | $SUDO tar -C /usr/local --strip-components=1 --no-overwrite-dir -xzf -
+
+        if [ "$MAKE_DEFAULT" = true ] && [ "$(realpath /usr/bin/ld)" != /usr/local/bin/mold ]; then
+          $SUDO ln -sf /usr/local/bin/mold "$(realpath /usr/bin/ld)"
+        fi
       shell: bash
       if: runner.os == 'linux'
+      env:
+        MOLD_VERSION: ${{ inputs.mold-version }}
+        MAKE_DEFAULT: ${{ inputs.make-default }}
